# Generated by Django 4.0.5 on 2022-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='name_id',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
